repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: black-format-all
        name: black format all files
        entry: .venv/bin/black --line-length=120 reference_api_buddy tests
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black, --line-length=120]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-typing-imports]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
        exclude: ^(tests/|smoke_tests/|test_.*\.py)

  - repo: local
    hooks:
      - id: black-check-all
        name: black --check reference_api_buddy tests
        entry: .venv/bin/black --check reference_api_buddy tests
        language: system
        pass_filenames: false
        always_run: true
        verbose: true
