name: Build and Publish to PyPI

on:
  release:
    types: [published]

permissions:
  contents: write  # needed for creating GitHub releases
  id-token: write  # needed for PyPI trusted publishing

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # Checkout the code at the released tag so the build matches the release
        ref: ${{ github.event.release.tag_name }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build wheels and sdist
      run: python -m build

    - name: Check package integrity
      run: twine check dist/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 7

  publish:
    needs: build
    runs-on: ubuntu-latest
    environment: release
    if: github.repository == 'tinkermonkey/reference-api-buddy'
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish package to PyPI
      # Requires PYPI_API_TOKEN secret to be configured in repository settings
      # See docs/RELEASE_SETUP.md for setup instructions
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
        print-hash: true
